In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
!pip install nltk spacy
import nltk
import spacy
import re

import en_core_web_sm
nlp = en_core_web_sm.load()

Requirement already satisfied: nltk in /opt/anaconda3/lib/python3.9/site-packages (3.7)
Requirement already satisfied: spacy in /opt/anaconda3/lib/python3.9/site-packages (3.5.0)
Requirement already satisfied: regex>=2021.8.3 in /opt/anaconda3/lib/python3.9/site-packages (from nltk) (2022.7.9)
Requirement already satisfied: click in /opt/anaconda3/lib/python3.9/site-packages (from nltk) (8.0.4)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.9/site-packages (from nltk) (4.64.1)
Requirement already satisfied: joblib in /opt/anaconda3/lib/python3.9/site-packages (from nltk) (1.0.1)
Requirement already satisfied: pathy>=0.10.0 in /opt/anaconda3/lib/python3.9/site-packages (from spacy) (0.10.1)
Requirement already satisfied: thinc<8.2.0,>=8.1.0 in /opt/anaconda3/lib/python3.9/site-packages (from spacy) (8.1.7)
Requirement already satisfied: numpy>=1.15.0 in /opt/anaconda3/lib/python3.9/site-packages (from spacy) (1.21.5)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /opt/anaconda3/lib/python3.9/site-packages (from spacy) (5.2.1)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /opt/anaconda3/lib/python3.9/site-packages (from spacy) (1.0.9)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /opt/anaconda3/lib/python3.9/site-packages (from spacy) (3.0.8)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.9/site-packages (from spacy) (2.28.1)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /opt/anaconda3/lib/python3.9/site-packages (from spacy) (2.4.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4 in /opt/anaconda3/lib/python3.9/site-packages (from spacy) (1.10.4)
Requirement already satisfied: typer<0.8.0,>=0.3.0 in /opt/anaconda3/lib/python3.9/site-packages (from spacy) (0.7.0)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.9/site-packages (from spacy) (2.11.3)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.9/site-packages (from spacy) (21.3)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /opt/anaconda3/lib/python3.9/site-packages (from spacy) (1.1.1)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.9/site-packages (from spacy) (63.4.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /opt/anaconda3/lib/python3.9/site-packages (from spacy) (3.3.0)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /opt/anaconda3/lib/python3.9/site-packages (from spacy) (2.0.7)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /opt/anaconda3/lib/python3.9/site-packages (from spacy) (1.0.4)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /opt/anaconda3/lib/python3.9/site-packages (from spacy) (2.0.8)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /opt/anaconda3/lib/python3.9/site-packages (from spacy) (3.0.12)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/anaconda3/lib/python3.9/site-packages (from packaging>=20.0->spacy) (3.0.9)
Requirement already satisfied: typing-extensions>=4.2.0 in /opt/anaconda3/lib/python3.9/site-packages (from pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4->spacy) (4.3.0)
Requirement already satisfied: charset-normalizer<3,>=2 in /opt/anaconda3/lib/python3.9/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.9/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2022.9.24)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.9/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/anaconda3/lib/python3.9/site-packages (from requests<3.0.0,>=2.13.0->spacy) (1.26.11)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /opt/anaconda3/lib/python3.9/site-packages (from thinc<8.2.0,>=8.1.0->spacy) (0.7.9)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /opt/anaconda3/lib/python3.9/site-packages (from thinc<8.2.0,>=8.1.0->spacy) (0.0.4)
Requirement already satisfied: MarkupSafe>=0.23 in /opt/anaconda3/lib/python3.9/site-packages (from jinja2->spacy) (2.0.1)

In [2]:
x = pd.read_csv('after_eda_audible.csv')
x.head()

,name,time,stars,price,ratings,releaseyear,releasemonth,has_verb,has_noun,has_adj,has_date
0,Geronimo Stilton #11 & #12,140,5.0,468.0,34.0,2008,8,0,1,0,0
1,The Burning Maze,788,4.5,820.0,41.0,2018,5,0,1,0,0
2,The Deep End,123,4.5,410.0,38.0,2020,11,0,1,0,0
3,Daughter of the Deep,676,4.5,615.0,12.0,2021,10,0,1,0,0
4,"The Lightning Thief: Percy Jackson, Book 1",600,4.5,820.0,181.0,2010,1,0,1,0,0

In [3]:
df = x.set_index('name')
df.head()

,time,stars,price,ratings,releaseyear,releasemonth,has_verb,has_noun,has_adj,has_date
name,,,,,,,,,,
Geronimo Stilton #11 & #12,140,5.0,468.0,34.0,2008,8,0,1,0,0
The Burning Maze,788,4.5,820.0,41.0,2018,5,0,1,0,0
The Deep End,123,4.5,410.0,38.0,2020,11,0,1,0,0
Daughter of the Deep,676,4.5,615.0,12.0,2021,10,0,1,0,0
"The Lightning Thief: Percy Jackson, Book 1",600,4.5,820.0,181.0,2010,1,0,1,0,0

In [4]:
#stars classification

def classify_stars(stars):
    if stars >= 5:
        return 1
    else:
        return 0

In [5]:
df['stars_class'] = df['stars'].apply(classify_stars)

In [6]:
df.head

<bound method NDFrame.head of                                             time  stars  price  ratings  \
name
Geronimo Stilton #11 & #12                   140    5.0  468.0     34.0
The Burning Maze                             788    4.5  820.0     41.0
The Deep End                                 123    4.5  410.0     38.0
Daughter of the Deep                         676    4.5  615.0     12.0
The Lightning Thief: Percy Jackson, Book 1   600    4.5  820.0    181.0
...                                          ...    ...    ...      ...
Why We Fly                                    56    5.0  100.0      1.0
River Town                                   876    5.0  836.0      1.0
Figures in a Landscape                      1004    4.0  949.0      1.0
Tower of London                                8    5.0   33.0      1.0
Tigers in the Snow                           294    5.0  702.0      1.0

                                            releaseyear  releasemonth  \
name
Geronimo Stilton #11 & #12                         2008             8
The Burning Maze                                   2018             5
The Deep End                                       2020            11
Daughter of the Deep                               2021            10
The Lightning Thief: Percy Jackson, Book 1         2010             1
...                                                 ...           ...
Why We Fly                                         2014             6
River Town                                         2010             5
Figures in a Landscape                             2018             6
Tower of London                                    2009            12
Tigers in the Snow                                 2004             8

                                            has_verb  has_noun  has_adj  \
name
Geronimo Stilton #11 & #12                         0         1        0
The Burning Maze                                   0         1        0
The Deep End                                       0         1        0
Daughter of the Deep                               0         1        0
The Lightning Thief: Percy Jackson, Book 1         0         1        0
...                                              ...       ...      ...
Why We Fly                                         1         0        0
River Town                                         0         1        0
Figures in a Landscape                             0         1        0
Tower of London                                    0         1        0
Tigers in the Snow                                 0         1        0

                                            has_date  stars_class
name
Geronimo Stilton #11 & #12                         0            1
The Burning Maze                                   0            0
The Deep End                                       0            0
Daughter of the Deep                               0            0
The Lightning Thief: Percy Jackson, Book 1         0            0
...                                              ...          ...
Why We Fly                                         0            1
River Town                                         0            1
Figures in a Landscape                             0            0
Tower of London                                    0            1
Tigers in the Snow                                 0            1

[15072 rows x 11 columns]>

In [7]:
columns_to_drop = ['stars', 'ratings']
df_features = df.drop(columns_to_drop, axis=1)
df_features.head()

,time,price,releaseyear,releasemonth,has_verb,has_noun,has_adj,has_date,stars_class
name,,,,,,,,,
Geronimo Stilton #11 & #12,140,468.0,2008,8,0,1,0,0,1
The Burning Maze,788,820.0,2018,5,0,1,0,0,0
The Deep End,123,410.0,2020,11,0,1,0,0,0
Daughter of the Deep,676,615.0,2021,10,0,1,0,0,0
"The Lightning Thief: Percy Jackson, Book 1",600,820.0,2010,1,0,1,0,0,0

In [8]:
df_features.stars_class.value_counts()

0    8311
1    6761
Name: stars_class, dtype: int64

In [9]:
#for classification, no need to scale
# Step 1: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df_features.drop(columns='stars_class'), df_features.stars_class, test_size=0.2, random_state=42)

In [10]:
X_train.shape

(12057, 8)

In [11]:
X_test.shape

(3015, 8)